### PR TITLE
simplifying build scripts

### PR DESCRIPTION
**Pull request by krober10nd**
#203 
* reduces unreadable boilerplate code to build cpp codes on the backend.
* now requiring pybind11 >= 2.6

### CODE REVIEW

**Comment by krober10nd** [comment]
@nschloe hey, hope all is well. I'm trying to migrate over to the new simplified pybind11 syntax for building the cpp codes. Locally when I build on my laptop, things seem to work but as you can see on the CI system none of the builds are able to find the compiled source codes. 

Any help when you can to figure out why that may be would be appreciated. 

P.S., I did not understand what the point of this first command after pybind11 (highlighted); I just made it _SeismicMesh but I suspect that may be a problem too. In pygalmesh it was `_pygalmesh` so I assumed it was the package name.

Screen Shot 2021-04-04 at 11 16 37 AM

**Comment by nschloe** [comment]
Your CPP module is called `_SeismicMesh`, not `.cpp...`

**Comment by krober10nd** [comment]
I see, thanks. In the previous build system, it put the *.so files in each directory so I could do relative module imports. Now I see that this produces one shared library with all them in it so will have to change them all to absolute imports I guess.

**Comment by krober10nd** [comment]
ah I think I can just create several pybind11 extensions in setup.py so that the *.so end up in the correct folders.

**Comment by krober10nd** [comment]
Now I get a bunch of 

```
E   ImportError: dynamic module does not define module export function (PyInit__SeismicMesh)
```

**Comment by krober10nd** [comment]
It's a naming issue. Working on the tedious fix.

**Comment by krober10nd** [comment]
cool tests all pass...

so now the user if they're using the recent PEP518 standard, then they will not have to manually install pybind11 as this is done via the pytoml file upon building?

**Comment by nschloe** [comment]
> so now the user if they're using the recent PEP518 standard, then they will not have to manually install pybind11 as this is done via the pytoml file upon building?

It's installed automatically, indeed.

**Comment by nschloe** [comment]
Biggest gain for you is probably this though:

screenshot

**Comment by krober10nd** [comment]
Yea I agree. The more lines, the more problems.

**Pull request merged**
