### PR TITLE
API overhaul

### PR DESCRIPTION
**Pull request by krober10nd**
Per #49, a major rework of the API by making the sizing class a function that, well, returns a sizing function as well as baking in the velocity model reading inside the class. 
```

 from sizing import *
 
 bbox = (-12e3, 0, 0, 67e3)
 fname = "vel_z6.25m_x12.5m_exact.segy"
 
 cell_size, bbox = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     wl=10.0,
     grade=0.15,
     grad=75.0,
     domain_ext=5000.0,
     pad_style="linear_ramp",
 )
 
 plot_sizing_function(cell_size, bbox)
```
where `cell_size` is a function. Note how I have to return the `bbox`;
Figure_1
 this is because the `domain_extension` has to change it.

In its simplest state, it just generates a constant resolution mesh of a default value of 150 m (relevant to these kind of domains). 

```
 from sizing import *
 
 bbox = (-12e3, 0, 0, 67e3)
 fname = "vel_z6.25m_x12.5m_exact.segy"
 
 cell_size, bbox = get_sizing_function_from_segy(
     fname,
     bbox,
 )
 
 plot_sizing_function(cell_size, bbox)

### CODE REVIEW

**Comment by krober10nd** [comment]
What remains to finish this PR is updating the tutorial, examples, and adding doc strings all reflecting the new public api.

**Comment by nschloe** [comment]
It's a bit weird that you specify `bbox`, pass it to `get_sizing_function_from_segy`, and get it back again:
```
 bbox = (-12e3, 0, 0, 67e3)
 fname = "vel_z6.25m_x12.5m_exact.segy"
 
 cell_size, bbox = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     wl=10.0,
     grade=0.15,
     grad=75.0,
     domain_ext=5000.0,
     pad_style="linear_ramp",
 )
```
If `get_sizing_function_from_segy` can get `bbox` from some files but not from others, I'd rather return `None` if it can't and set `bbox` explicitly in that case. If it never can, remove bbox from this entirely.

**Comment by krober10nd** [comment]
That make sense, but I return `bbox` also because it's modified if the user chooses to extend the domain (which has implications on the sizing function).

**Comment by krober10nd** [comment]
I suppose if the user activates the `domain_ext`, it will return a new` bbox`?

**Comment by nschloe** [comment]
That's mildly confusing. Please explain to me exactly what data is contained in a segy file.

**Comment by krober10nd** [comment]
> Please explain to me exactly what data is contained in a segy file.

Scalar data on a grid. 

For seismic wave propagation, the user typically extends the domain. In the domain extension, there's some form of mesh adaptation. I give the user the option to extend the domain a variable width and apply some mesh adaptation heuristic there.

**Comment by nschloe** [comment]
> Scalar data on a grid.

A Cartesian grid parallel to the axes? With dimensions? How many scalar variables?

**Comment by krober10nd** [comment]
> A Cartesian grid parallel to the axes? With dimensions? How many scalar variables?

A regular Cartesian grid, yes, axis-aligned. With either 2 or 3 dimensions. Frequently for what we do, 1 scalar variable but can be more.

**Comment by nschloe** [comment]
Okay, in this case you don't need no `domain_ext`; the size info is all in `bbox`. If the user wants a domain ten times as big, just make the `bbox` bigger. No need to return `bbox` either then.

**Comment by krober10nd** [comment]
Well, there's no information regarding the `bbox` in the segy file. So if the user just passes a bigger `bbox` then this will create problems. For instance, the grid spacings of the velocity model will be different than what they are supposed to be distorting the model.

The best I think I can do is remove the return of `bbox` from `get_sizing_from_segy` if the the user is not using the `domain_ext` mesh adaptation heuristic.

**Comment by krober10nd** [comment]
What would think if I added this `domain_ext` information to the definition of the `bbox`?

**Comment by krober10nd** [comment]
Like:
```
bbox = (0,1,0,1)
try:
    x1,x2, y1, y2, x_ext, y_ext = bbox
except ValueError:
    x1,x2, y1, y2 = bbox
```

**Comment by nschloe** [comment]
Please explain the meaning of the arguments in
```
 cell_size, bbox = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     wl=10.0,
     grade=0.15,
     grad=75.0,
     domain_ext=5000.0,
     pad_style="linear_ramp",
 )
```
to me. (And other arguments that may not be listed here.)

**Comment by krober10nd** [comment]
https://seismicmesh.readthedocs.io/en/api_overhaul/api.html#SeismicMesh.sizing.get_sizing_function_from_segy

**Comment by krober10nd** [comment]
It's a work in progress the documentation. It's a lot to maintain. So I apologize in advance for any mistakes.

**Comment by nschloe** [comment]
I don't understand the difference between bbox and domain_extension. Can you elaborate?

**Comment by krober10nd** [comment]
> I don't understand the difference between bbox and domain_extension. Can you elaborate?

The `bbox` is a tuple of coordinates representing the corner coordinates of the *velocity model*.  

The `domain_extension` is an additional artificial region of fixed width (`domain_ext`) bordering the +x, -x, -z, (and +y, -y if 3d) axes around the velocity model.  It is used to absorb outgoing/reflected waves in simulations with the generated mesh in numerical simulations.

 In this bordering layer, I have support for several mesh adaptation heuristics (`pad_style`) to size cells. For example, in the `linear_ramp`, the mesh cell size grows linearly from the values along the edges of the original velocity model to width `domain_ext` to conserve on total degrees of freedom in the mesh.

**Comment by nschloe** [comment]
Okay, so the cell_size_function is defined on the `domain_extension`, and the bbox of the file is smaller than that. The mesh is later generated on the `domain_extension`. Is this correct?

**Comment by krober10nd** [comment]
> Okay, so the cell_size_function is defined on the domain_extension, and the bbox of the file is smaller than that.

Yes. The bbox of the file is smaller than that *if* the domain_extension is in use. 

>  The mesh is later generated on the domain_extension. Is this correct?

Yes.

**Comment by nschloe** [comment]
I'd call it `domain_padding` or `bbox_padding` then. I'd also suggest to separate the reader and the function generator, something like
```
velocity_data = read_segy(filename, ...)
bbox = ( ... )

cell_size_function = generate_cell_size_function(velocity_data, bbox, ...)
```
This makes clearer which arguments do what, and you could separate out the options that are only interesting for binary reads. Also, perhaps there are other, more modern file formats which include the bbox and could be supported this way.

**Comment by krober10nd** [comment]
> Edit:
What do you think about another suggestion: Don't return a function, but a Python object that has obj.bbox and obj.eval.

Hm, I like that one. The other more modern file formats could be supported inside some private functions inside the `get_sizing_function_from_segy` module and detected by their suffix.

Then in `generate_mesh` I would check for that object and unpack it. Otherwise, it's the standard procedure with the original bbox.

**Comment by krober10nd** [comment]
This would reduce the input args to `generate_mesh` too.

**Comment by nschloe** [comment]
g

Cool. Would you like to work on this and ping me when it's ready?

**Comment by krober10nd** [comment]
Yes.
bk7mb

**Comment by krober10nd** [comment]
Ok I implemented a simple sizing function class. 

```
 class SizeFunction:
     def __init__(self, bbox, cell_size):
         if not isinstance(bbox, tuple):
             raise ValueError("`bbox` must be a tuple")
         self.bbox = bbox
         if not callable(cell_size):
             raise ValueError("`cell_size` must be callable")
         self.cell_size = cell_size
 
     def eval(self, x):
         return self.cell_size(x)
```

```
 from SeismicMesh import get_sizing_function_from_segy, plot_sizing_function
 
 bbox = (-12e3, 0, 0, 67e3)
 fname = "vel_z6.25m_x12.5m_exact.segy"
 
 cell_size = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     grad=75.0,
     domain_pad=5000.0,
     pad_style="linear_ramp",
 )
 
 plot_sizing_function(cell_size)

**Comment by nschloe** [comment]
You could just  `self.eval = cell_size` I think. Doesn't really matter though; looks good to me.

**Comment by krober10nd** [comment]
I think I'll put the ``rectangle``/``cube`` geometry as a field of the `SizingClass` as well as this avoids the need to import geometry into the script.

**Comment by krober10nd** [comment]
I was doing this previously:

```
sizing function blah blah...

def cube(p):
     return geometry.dblock(p, *bbox)
 
 
 points, cells = generate_mesh(
     bbox=bbox, h0=hmin, cell_size=ef, signed_distance_function=cube
 )
```

**Comment by nschloe** [comment]
And your plan?

**Comment by krober10nd** [comment]
Something like this:

```
 from SeismicMesh import (
     get_sizing_function_from_segy,
     plot_sizing_function,
     generate_mesh,
 )
 
 bbox = (-12e3, 0, 0, 67e3)
 fname = "vel_z6.25m_x12.5m_exact.segy"
     
 cell_size = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     grad=75.0,
     domain_pad=5000.0,
     pad_style="linear_ramp",
 )
  
 points, cells = generate_mesh(cell_size, h0=75.0)
```

where the object of `SizeFunction` has a field `signed_distance_function`.

**Comment by nschloe** [comment]
Typically, `generate_mesh` functions take a `domain` and some mesh size parameters (`max_edge_size`, `cell_size` etc.). I assume `h0` is the initial edge size for distmesh. (One could also deduce this from `cell_size` by evaluatuting it "everywhere" and taking the average.)

I'd stick to this signature, too. I think it's even worth wrapping the `bbox` in a `Rectangle` or `Cube` object.

**Comment by krober10nd** [comment]
So...something like this?

```
 from SeismicMesh import (
     get_sizing_function_from_segy,
     plot_sizing_function,
     generate_mesh,
     Rectangle
 )
 
 bbox = (-12e3, 0, 0, 67e3)
 fname = "vel_z6.25m_x12.5m_exact.segy"
     
 size_func = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     grad=75.0,
     domain_pad=5000.0,
     pad_style="linear_ramp",
 )
 rectangle = Rectangle(bbox)
 points, cells = generate_mesh(cell_size = size_func, domain=rectangle, h0=75.0)

**Comment by nschloe** [comment]
This looks good I think. I'd always put the domain first though and make it mandatory.

**Comment by krober10nd** [comment]
Ok great.

 Then for example, in the case the `Rectangle` is indeed a Rectangle class object, I can check its internal domain extents against the ``cell_size`` object ``bbox`` and retain the larger of the two in the name/value parsing of `genereate_mesh``. This resolves the annoyance with the `bbox` changing when a `domain_pad` is used. 

I don't expect you'd be doing the domain padding business if you aren't using a cell size object anyway.

**Comment by nschloe** [comment]
Yeah, for example.

**Comment by krober10nd** [comment]
Cool, this looks very nice now.

```
 from SeismicMesh import (
     get_sizing_function_from_segy,
     plot_sizing_function,
     generate_mesh,
     Rectangle,
 )
 
 bbox = (-12e3, 0, 0, 67e3)
 fname = "vel_z6.25m_x12.5m_exact.segy"
 
 rectangle = Rectangle(bbox)
 
 cell_size = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     grad=75.0,
     domain_pad=5000.0,
     pad_style="linear_ramp",
 )
 
 plot_sizing_function(cell_size)
 
 points, cells = generate_mesh(rectangle, cell_size, h0=75.0)
```

**Comment by nschloe** [comment]
Looks good to me too. If you merge and release, I can play around with it a little bit.

**Comment by krober10nd** [comment]
Yea, that's the plan for later this afternoon (in Brazil).

**Pull request merged**
