### PR TITLE
switching to svg for figures

### PR DESCRIPTION
**Pull request by krober10nd**
#168

### CODE REVIEW

**Comment by nschloe** [comment]
The ylim should always be 0 in the figures.

**Comment by nschloe** [comment]
Also, some plots still have ylabels.

**Comment by krober10nd** [comment]
> Also, some plots still have ylabels.


Yes, the second plot does by design. I prefer it.

**Comment by nschloe** [comment]
> Yes, the second plot does by design. I prefer it.

title and ylabel virtually say the same thing (`Speedup T1/TC` vs `Parallel Speedup`, `Mesh generation rate (vertices/sec)` vs `Mesh generation rate`). One of the two is redundant. I'd remove the one that's harder the read, and merge the units into the one that remains.

**Pull request merged**
