### PR TITLE
pep8 compliance

### PR DESCRIPTION
**Pull request by krober10nd**
Ensuring compliance with [pep8](https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables) per #48 

1) All functions, variables, and methods obey snake_case. 

2) All classes obey CapsCase.

### CODE REVIEW

**Comment by nschloe** [comment]
test_README failed. Ha! :+1:

**Comment by krober10nd** [comment]
haha, yes I'm a full believe in tests now. 👍 💯  Changing the api breaks everything and it helps enormously.

**Comment by nschloe** [comment]
The changes in PR looks very good. One could even go a step further and look at the module name `SeismicMesh`. I for one am not aware of any Python package that uses capital letters. For package names, I usually stick to all small letters with no underscores/hyphens. This makes it possible to tell the user to `pip install foobar` and `import foobar`.  Since this is a more intrusive call and not strictly necessary, I'll leave it up to you. In any case, something to keep in mind for the future.

**Comment by krober10nd** [comment]
looks like LGTM is helping also find what things broke in the API as it changes. Neat.

**Comment by nschloe** [comment]
> looks like LGTM is helping also find what things broke in the API as it changes. Neat.

Yeah, didn't know that either.

**Comment by krober10nd** [comment]
> The changes in PR looks very good.

Awesome, thank you. I'm finishing up some of the remaining modules and will post shortly. Then I'll tackle the more complex changes that need to happen to the public API that you suggested in the other issue. 

> One could even go a step further and look at the module name SeismicMesh. I for one am not aware of any Python package that uses capital letters. For package names, I usually stick to all small letters with no underscores/hyphens. This makes it possible to tell the user to pip install foobar and import foobar. Since this is a more intrusive call and not strictly necessary, I'll leave it up to you. In any case, something to keep in mind for the future.

Interesting! I clearly didn't realize this. Well, I don't know how that would work with the submitted manuscript and some people here using the programs. So for now, I'd rather leave it as is since it might confuse a bit of people. Definitely for my future developments I'll keep it mind and adhere to the standards.

**Pull request merged**
