### PR TITLE
fix to setup.cfg

### PR DESCRIPTION
**Pull request by krober10nd**
* testing 3.8.1 
* removing installation blocker in setup.cfg for Python versions > 3.8.0

### CODE REVIEW

**Comment by krober10nd** [comment]
@nschloe maybe you have some hints as to what may cause an error such as this? 

maybe it has to do with the order of the builds? 

https://app.circleci.com/pipelines/github/krober10nd/SeismicMesh/1017/workflows/489009eb-74b0-43b4-8d9b-097551347021/jobs/2003

**Comment by krober10nd** [comment]
@ncshloe so that was challenging. Turns out the docker for Python 3.8.1 had a conflicting version of `virtualenv` which lead to some missing module problem. The solution was to uninstall `virtualenv` for 3.8.1. 

Anyway, I can add other Python builds too if you like. I'm not sure what you consider to be "well-tested" per your issue #158  since there's literally dozens of Python versions between 3 and 3.9. Please let me know.

**Comment by nschloe** [comment]
I usually go for one per supported Python minor, e.g., 3.6.x, 3.7.y, 3.8.z.

https://github.com/nschloe/dmsh/blob/master/.github/workflows/ci.yml#L27

**Comment by krober10nd** [comment]
looks like a server that hosts libopenmpi failed or blocked the simultaneous queries.

**Comment by nschloe** [comment]
You may want to look at github-actions.

**Comment by krober10nd** [comment]
> You may want to look at github-actions.


Yea this is quite annoying.

**Comment by krober10nd** [comment]
ah there's a spacing problem with the 3.6.1 build. I'm just guessing at the syntax here.

**Comment by krober10nd** [comment]
this issue with 3.6.1 not finding open MPI is related to the apt-get not having up-to-date package information.

**Comment by krober10nd** [comment]
Regardless of GitHub actions or CircleCI I still will need to build things from source unless I create my own docker. It seems that the default Python version dockers provided by CI also were created on old versions of the Debian. I wonder if there is a way to get the older versions of Python on the most recent LTS?

**Comment by krober10nd** [comment]
ah so got the 3.6.5 to run but looks like a CPP error now was caught with an older compiler. Interesting. I'll have to activate the docker to see how to repeat the compilation error..

**Pull request merged**
