### PR TITLE
adding optimization benchmarks

### PR DESCRIPTION
**Pull request by krober10nd**
* @jorgensd I created a new benchmark similar to the old ball one where a mesh improvement method is ran at the end to compare final qualities with improvement methods. Specifically, I use the default gmsh 3d optimization one (not Netgen).

* The results from running the `benchmarks/benchmark_ball_optmi.py` 
Time spent in optimization is generally between 0.20 to 0.33 seconds between the methods. 
The times reported below are without optimization considered.
Screen Shot 2020-10-13 at 11 17 19 AM

### CODE REVIEW

**Comment by krober10nd** [comment]
* If I run the ball benchmark with 50 meshing iterations (instead of 25), I get an even better final quality with mesh improvement but obviously slower. 

Screen Shot 2020-10-13 at 11 23 38 AM

**Comment by jorgensd** [comment]
Happy that the mesh optimization helps improving the mesh. Does the gmsh one improve when running optimization on it? (I thought gmsh used optimization in 3D by default). 
I would like to note that even if the average mesh quality goes up, the minimum mesh quality seems to decrease when you increase number of iterations (from 13.173 to 12.174). I'm not trying to say that this is disastrous, but I am then unsure if it is worth having more iterations (as the runtime increases with 60 percent). I guess your algorithm will always keep the dihedral algorithm over the minimum bound (default 10).

To try to draw some conclusions out of this:
- The meshing algorithm you are using in your software has to use the sliver removal software to ensure a non-degenerate mesh in 3D.
- This algorithm is currently time consuming and only runs in serial (I guess there is a mpi gather operations after parallel mesh generation to fix this).
- On average, the mesh quality using sliver removal increases, but it is a time consuming approach which one should run relatively few number of iterations of.
- Other optimization software, such as the GMSH optimize can further improve the mesh quality. The standard algorithm is quite fast.
- The NETGEN optimization algorithm can increase the cell quality to levels the sliver removal software struggles to achieve. At least on these simplistic geometries, the NETGEN optimization makes to runtime of the GMSH generation ~= SeismicMesh, where Seismic mesh has the higher average quality, while GMSH has the best minimum quality cells.

**Comment by jorgensd** [comment]
> > Does the gmsh one improve when running optimization on it? (I thought gmsh used optimization in 3D by default).
> 
> All the above call the same optimization at the end.

I got that, but does this last optimization call actually improve the GMSH mesh?

**Comment by krober10nd** [comment]
> I would like to note that even if the average mesh quality goes up, the minimum mesh quality seems to decrease when you increase number of iterations (from 13.173 to 12.174). I'm not trying to say that this is disastrous, but I am then unsure if it is worth having more iterations (as the runtime increases with 60 percent). I guess your algorithm will always keep the dihedral algorithm over the minimum bound (default 10).

Yes, 10 degree as a bound seems to work quite well. You I believe you can also achieve higher dihedral bounds by repeatedly calling this method with progressively higher bounds. 

This algorithm works by perturbing a vertex of the tetrahedral a fraction the minimum edge length in the domain in the direction that increases circumsphere radii of the sliver the fastest. I could make the `sliver_removal` algorithm parallel but actually it already accelerates as there are fewer slivers since I use CGAL's incremental point `moves` capability (and avoid a full retriangulation at all costs).

**Comment by krober10nd** [comment]
Ah, the par3d to master switch today didn't carry over some critical thing on master...

**Comment by krober10nd** [comment]
I can get a dihedral bound of 20 degrees in about a second with the following.
```
 import gmsh
 import SeismicMesh
 import meshio
 
 cube = SeismicMesh.Cube((0.0, 1.0, 0.0, 1.0, 0.0, 1.0))
 points, cells = SeismicMesh.generate_mesh(domain=cube, edge_length=0.05)
 points, cells = SeismicMesh.sliver_removal(points=points, domain=cube, edge_length=0.05)
 points, cells = SeismicMesh.sliver_removal(
     points=points, domain=cube, edge_length=0.05, min_dh_angle_bound=15
 )
 points, cells = SeismicMesh.sliver_removal(
     points=points, domain=cube, edge_length=0.05, min_dh_angle_bound=20
 )
```

**Comment by krober10nd** [comment]
This optimization benchmark came on in a different PR by accident so I'm going to close this.

**Pull request closed without merging**
